name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DOTNET_VERSION: 3.1.301

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Job setup
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Build, test and pack/publish
      - name: Build and Test
        run: ./Build.ps1
        shell: pwsh

      # Upload artifacts
      - name: Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts.zip
          path: artifacts/**/*
