name: .NET Core

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Install dependencies
        run: dotnet restore ./AnonymousTokens.sln
      - name: Build AnonymousTokens
        run: dotnet build --configuration Release --no-restore ./src/AnonymousTokens/AnonymousTokens.csproj
      - name: Build ClientServer-sample client
        run: dotnet build --configuration Release --no-restore ./samples/ClientServer/Client/Client.Console/Client.Console.csproj
      - name: Build ClientServer-sample token-generation api
        run: dotnet build --configuration Release --no-restore ./samples/ClientServer/Server/Server.TokenGeneration.Api/Server.TokenGeneration.Api.csproj
      - name: Build ClientServer-sample token-verification api
        run: dotnet build --configuration Release --no-restore ./samples/ClientServer/Server/Server.TokenVerification.Api/Server.TokenVerification.Api.csproj
      - name: Run UnitTests
        run: dotnet test --configuration Release --no-restore ./test/AnonymousTokens.UnitTests/AnonymousTokens.UnitTests.csproj
