name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ./src/AnonymousTokens.sln
    - name: Build client
      run: dotnet build --configuration Release --no-restore .\src\Client\Client.Console\Client.Console.csproj
    - name: Build backend api
      run: dotnet build --configuration Release --no-restore .\src\Server\Server.Backend.Api\Server.Backend.Api.csproj
    - name: Build verification api
      run: dotnet build --configuration Release --no-restore .\src\Server\Server.VerificationBackend.Api\Server.VerificationBackend.Api.csproj     
